name: NameEffects
main: net.betterverse.nameeffects.NameEffects
version: 0.1
authors: [ZNickq]
commands:
  alias:
    usage: Invalid usage or no permissions!
  prefix:
    usage: Invalid usage or no permissions!