name: NameEffects
main: net.betterverse.nameeffects.NameEffects
version: 0.2
authors: [ZNickq]
softdepend: [Vault, CreditsShop]
commands:
  alias:
    usage: Invalid usage or no permissions!
  prefix:
    usage: Invalid usage or no permissions!