name: Alias
main: net.betterverse.alias.Alias
version: 2.0.0
commands:
  alias:
    description: Allows you to set an alias.
    usage: /alias <nickname>
    permission: alias.use
permissions:
  alias.use:
    description: Allows you to set an alias.